/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_alberthgodoy;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author godoy
 */
public class Examen2P2_AlberthGodoy extends javax.swing.JFrame {

    private ArrayList<Empleado> listaEmpleado = new ArrayList();
    private ArrayList<Carros> listaCarros = new ArrayList();

    /**
     * Creates new form Examen2P2_AlberthGodoy
     */
    public Examen2P2_AlberthGodoy() {
        initComponents();
        listaEmpleado = new ArrayList();
        administrarEmpleado admin = new administrarEmpleado("./Nube/empleado.alex");
        admin.cargarArchivoEmpleado();
        listaEmpleado = admin.getListaEmpleado();
        cargarJtableEmpleado(jTable_Empleados, listaEmpleado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel_CrudEmpleados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_NumIdentidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_Edad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jTextField_NombreEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane_Empleados = new javax.swing.JScrollPane();
        jTable_Empleados = new javax.swing.JTable();
        jButton_CrearEmpleado = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_CrudEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Crear Empleados");
        jPanel_CrudEmpleados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 106, -1));
        jPanel_CrudEmpleados.add(jTextField_NumIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 140, 30));

        jLabel2.setText("Nombre");
        jPanel_CrudEmpleados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setText("Edad");
        jPanel_CrudEmpleados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 40, -1));

        jSpinner_Edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel_CrudEmpleados.add(jSpinner_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 60, -1));

        jLabel4.setText("Numero Identidad");
        jPanel_CrudEmpleados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 100, -1));
        jPanel_CrudEmpleados.add(jTextField_NombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 30));

        jLabel5.setText("Eliminar Empleados");
        jPanel_CrudEmpleados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jTable_Empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Num Identidad", "Carros Reparados"
            }
        ));
        jScrollPane_Empleados.setViewportView(jTable_Empleados);

        jPanel_CrudEmpleados.add(jScrollPane_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 770, 330));

        jButton_CrearEmpleado.setText("Crear Empleado");
        jButton_CrearEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CrearEmpleadoMouseClicked(evt);
            }
        });
        jPanel_CrudEmpleados.add(jButton_CrearEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 100, 30));

        jButton1.setText("Eliminar Empleado");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel_CrudEmpleados.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 120, 30));

        jTabbedPane.addTab("Crear / Eliminar Empleados", jPanel_CrudEmpleados);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane.addTab("Crear/Eliminar Carros", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CrearEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CrearEmpleadoMouseClicked
        //Crear Empleados

        try {
            //Cargar archivos
            listaEmpleado = new ArrayList();
            administrarEmpleado admin = new administrarEmpleado("./Nube/empleado.alex");
            admin.cargarArchivoEmpleado();
            listaEmpleado = admin.getListaEmpleado();
            String nombre = jTextField_NombreEmpleado.getText();
            int edad = (int) jSpinner_Edad.getValue();
            String numID = jTextField_NumIdentidad.getText();
            int carrosExitos = 0;
            //Validar
            for (Empleado empleado : listaEmpleado) {
                if (empleado.getNumID().equals(numID)) {
                    throw new Exception("Ya esta ese id");
                }

            }
            //Crear Empleaod
            listaEmpleado.add(new Empleado(nombre, edad, numID, carrosExitos));
            //Cargar Archivo
            admin.setListaEmpleado(listaEmpleado);
            admin.escribirArchivoEmpleado();
            cargarJtableEmpleado(jTable_Empleados, listaEmpleado);
            JOptionPane.showMessageDialog(jPanel_CrudEmpleados, "Empleado Creado", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jPanel_CrudEmpleados, e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_CrearEmpleadoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jTable_Empleados.getSelectedRowCount() == 1) {
            listaEmpleado = new ArrayList();
            administrarEmpleado admin = new administrarEmpleado("./Nube/empleado.alex");
            admin.cargarArchivoEmpleado();
            DefaultTableModel model = (DefaultTableModel) jTable_Empleados.getModel();
            //Eliminar el empleado seleccionado
            String numID = (String) model.getValueAt(jTable_Empleados.getSelectedRow(), 2);
            for (int i = 0; i < listaEmpleado.size(); i++) {
                Empleado empleadoSelect = listaEmpleado.get(i);
                if (empleadoSelect.getNumID().equals(numID)) {
                    listaEmpleado.remove(empleadoSelect);
                }
            }
            //Eliminar de Archivos
            admin.setListaEmpleado(listaEmpleado);
            admin.escribirArchivoEmpleado();
            cargarJtableEmpleado(jTable_Empleados, listaEmpleado);
            JOptionPane.showMessageDialog(jPanel_CrudEmpleados, "Empleado Removido", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(jPanel_CrudEmpleados, "No selecciono nada", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1MouseClicked
    public void cargarJtableEmpleado(JTable jTable, ArrayList<Empleado> listaEmpleados) {
        //Agarrar el modelo
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setRowCount(0);
        for (int i = 0; i < listaEmpleados.size(); i++) {
            Empleado empleadoSelected = listaEmpleados.get(i);
            Object[] newRow = {
                empleadoSelected.getNombre(),
                empleadoSelected.getEdad(),
                empleadoSelected.getNumID(),
                empleadoSelected.getCantCarrosreparadoExito()
            };
            model.addRow(newRow);
        }
        jTable.setModel(model);
        jTable.repaint();
        jTable.updateUI();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen2P2_AlberthGodoy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_CrearEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_CrudEmpleados;
    private javax.swing.JScrollPane jScrollPane_Empleados;
    private javax.swing.JSpinner jSpinner_Edad;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable_Empleados;
    private javax.swing.JTextField jTextField_NombreEmpleado;
    private javax.swing.JTextField jTextField_NumIdentidad;
    // End of variables declaration//GEN-END:variables
}
