/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_alberthgodoy;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author godoy
 */
public class Examen2P2_AlberthGodoy extends javax.swing.JFrame {

    private ArrayList<Empleado> listaEmpleado = new ArrayList();
    private ArrayList<Carros> listaCarros = new ArrayList();
    private SimpleDateFormat dFormat = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form Examen2P2_AlberthGodoy
     */
    public Examen2P2_AlberthGodoy() {
        initComponents();
        listaEmpleado = new ArrayList();
        administrarEmpleado admin = new administrarEmpleado("./Nube/empleado.alex");
        admin.cargarArchivoEmpleado();
        listaEmpleado = admin.getListaEmpleado();
        cargarJtableEmpleado(jTable_Empleados, listaEmpleado);
        listaCarros = new ArrayList();
        admin = new administrarEmpleado("./Nube/carros.alex");
        admin.cargarArchivoCarros();
        listaCarros = admin.getListaCarros();
        cargarJtableCarros(jTable_Carros, listaCarros);
        cargarJcomboBoxCarros(jComboBox_ModificarCarros, listaCarros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel_CrudEmpleados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_NumIdentidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_Edad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jTextField_NombreEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane_Empleados = new javax.swing.JScrollPane();
        jTable_Empleados = new javax.swing.JTable();
        jButton_CrearEmpleado = new javax.swing.JButton();
        jButton_EliminarEmpleado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Marca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Modelo = new javax.swing.JTextField();
        jTextField_CostoReparacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_NumID = new javax.swing.JTextField();
        jButton_CrearCarros = new javax.swing.JButton();
        jScrollPane_Empleados1 = new javax.swing.JScrollPane();
        jTable_Carros = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Fecha = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jComboBox_ModificarCarros = new javax.swing.JComboBox<>();
        jTextField_MarcaModificar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_NumIDModificar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_CostoReparacionModificar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_ModeloModificar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_FechaModificar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton_SeleccionarCarro = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBox_EmpleadoReparar = new javax.swing.JComboBox<>();
        jComboBox_AutoReparar = new javax.swing.JComboBox<>();
        jProgressBar_CargaSimulacion = new javax.swing.JProgressBar();
        jButton_SIMULAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Simulacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneStateChanged(evt);
            }
        });

        jPanel_CrudEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Crear Empleados");
        jPanel_CrudEmpleados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 106, -1));
        jPanel_CrudEmpleados.add(jTextField_NumIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 140, 30));

        jLabel2.setText("Nombre");
        jPanel_CrudEmpleados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setText("Edad");
        jPanel_CrudEmpleados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 40, -1));

        jSpinner_Edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel_CrudEmpleados.add(jSpinner_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 60, -1));

        jLabel4.setText("Numero Identidad");
        jPanel_CrudEmpleados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 100, -1));
        jPanel_CrudEmpleados.add(jTextField_NombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 30));

        jLabel5.setText("Eliminar Empleados");
        jPanel_CrudEmpleados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jTable_Empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Num Identidad", "Carros Reparados"
            }
        ));
        jScrollPane_Empleados.setViewportView(jTable_Empleados);

        jPanel_CrudEmpleados.add(jScrollPane_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 770, 330));

        jButton_CrearEmpleado.setText("Crear Empleado");
        jButton_CrearEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CrearEmpleadoMouseClicked(evt);
            }
        });
        jPanel_CrudEmpleados.add(jButton_CrearEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 100, 30));

        jButton_EliminarEmpleado.setText("Eliminar Empleado");
        jButton_EliminarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EliminarEmpleadoMouseClicked(evt);
            }
        });
        jPanel_CrudEmpleados.add(jButton_EliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 120, 30));

        jTabbedPane.addTab("Crear / Eliminar Empleados", jPanel_CrudEmpleados);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Crear Carros");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 20));

        jLabel7.setText("Marca");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, -1));
        jPanel2.add(jTextField_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 30));

        jLabel8.setText("Modelo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 40, -1));
        jPanel2.add(jTextField_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 150, 30));
        jPanel2.add(jTextField_CostoReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 150, 30));

        jLabel9.setText("Costo de Reparacion");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 120, -1));

        jLabel10.setText("Num ID");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 40, -1));
        jPanel2.add(jTextField_NumID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));

        jButton_CrearCarros.setText("Crear Carros");
        jButton_CrearCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CrearCarrosMouseClicked(evt);
            }
        });
        jPanel2.add(jButton_CrearCarros, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 90, 30));

        jTable_Carros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Año Fabricacion", "Estado Vehiculo", "Costo Reparacion"
            }
        ));
        jScrollPane_Empleados1.setViewportView(jTable_Carros);

        jPanel2.add(jScrollPane_Empleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 770, 330));

        jLabel11.setText("Fecha");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 40, -1));
        jPanel2.add(jTextField_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 150, 30));

        jTabbedPane.addTab("Crear/Eliminar Carros", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.add(jComboBox_ModificarCarros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 750, 30));
        jPanel3.add(jTextField_MarcaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 30));

        jLabel12.setText("Marca");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, -1));
        jPanel3.add(jTextField_NumIDModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, 30));

        jLabel13.setText("Num ID");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 40, -1));
        jPanel3.add(jTextField_CostoReparacionModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 150, 30));

        jLabel14.setText("Costo de Reparacion");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 120, -1));
        jPanel3.add(jTextField_ModeloModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 30));

        jLabel15.setText("Modelo");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 40, -1));
        jPanel3.add(jTextField_FechaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 150, 30));

        jLabel16.setText("Fecha");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 40, -1));

        jButton1.setText("Modificar Carro");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 100, -1));

        jButton_SeleccionarCarro.setText("Seleccionar Carro");
        jButton_SeleccionarCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SeleccionarCarroMouseClicked(evt);
            }
        });
        jPanel3.add(jButton_SeleccionarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 120, -1));

        jTabbedPane.addTab("Modificar Carro", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(jComboBox_EmpleadoReparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 36, 349, -1));

        jPanel1.add(jComboBox_AutoReparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 36, 402, -1));
        jPanel1.add(jProgressBar_CargaSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 104, 769, 29));

        jButton_SIMULAR.setText("SIMULAR");
        jButton_SIMULAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SIMULARMouseClicked(evt);
            }
        });
        jPanel1.add(jButton_SIMULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, -1));

        jTable_Simulacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Empleado", "Carro Reparar", "Reparacion Exitosa"
            }
        ));
        jScrollPane1.setViewportView(jTable_Simulacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 750, 330));

        jTabbedPane.addTab("Simulacion", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CrearEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CrearEmpleadoMouseClicked
        //Crear Empleados

        try {
            //Cargar archivos
            listaEmpleado = new ArrayList();
            administrarEmpleado admin = new administrarEmpleado("./Nube/empleado.alex");
            admin.cargarArchivoEmpleado();
            listaEmpleado = admin.getListaEmpleado();
            String nombre = jTextField_NombreEmpleado.getText();
            int edad = (int) jSpinner_Edad.getValue();
            String numID = jTextField_NumIdentidad.getText();
            int carrosExitos = 0;
            //Validar
            for (Empleado empleado : listaEmpleado) {
                if (empleado.getNumID().equals(numID)) {
                    throw new Exception("Ya esta ese id");
                }

            }
            //Crear Empleaod
            listaEmpleado.add(new Empleado(nombre, edad, numID, carrosExitos));
            //Cargar Archivo
            admin.setListaEmpleado(listaEmpleado);
            admin.escribirArchivoEmpleado();
            cargarJtableEmpleado(jTable_Empleados, listaEmpleado);
            jTextField_NombreEmpleado.setText("");
            jSpinner_Edad.setValue(0);
            jTextField_NumIdentidad.setText("");
            JOptionPane.showMessageDialog(jPanel_CrudEmpleados, "Empleado Creado", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jPanel_CrudEmpleados, e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_CrearEmpleadoMouseClicked

    private void jButton_EliminarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EliminarEmpleadoMouseClicked
        if (jTable_Empleados.getSelectedRowCount() == 1) {
            listaEmpleado = new ArrayList();
            administrarEmpleado admin = new administrarEmpleado("./Nube/empleado.alex");
            admin.cargarArchivoEmpleado();
            DefaultTableModel model = (DefaultTableModel) jTable_Empleados.getModel();
            //Eliminar el empleado seleccionado
            String numID = (String) model.getValueAt(jTable_Empleados.getSelectedRow(), 2);
            for (int i = 0; i < listaEmpleado.size(); i++) {
                Empleado empleadoSelect = listaEmpleado.get(i);
                if (empleadoSelect.getNumID().equals(numID)) {
                    listaEmpleado.remove(empleadoSelect);
                }
            }
            //Eliminar de Archivos
            admin.setListaEmpleado(listaEmpleado);
            admin.escribirArchivoEmpleado();
            cargarJtableEmpleado(jTable_Empleados, listaEmpleado);
            JOptionPane.showMessageDialog(jPanel_CrudEmpleados, "Empleado Removido", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(jPanel_CrudEmpleados, "No selecciono nada", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_EliminarEmpleadoMouseClicked

    private void jButton_CrearCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CrearCarrosMouseClicked
        //Crear Carross

        try {
            //Cargar archivos
            listaCarros = new ArrayList();
            administrarEmpleado admin = new administrarEmpleado("./Nube/carros.alex");
            admin.cargarArchivoCarros();
            listaCarros = admin.getListaCarros();
            String marca = jTextField_Marca.getText();
            String modelo = jTextField_Modelo.getText();
            String numID = jTextField_NumID.getText();
            double costoReparacion = Double.parseDouble(jTextField_CostoReparacion.getText());
            String estadoReparacion = "EN ESPERA";
            String fecha = jTextField_Fecha.getText();
            //Convertir a Date 
            Date fechaReparacion = dFormat.parse(fecha);
            //Validar
            for (Carros carros : listaCarros) {
                if (carros.getID().equals(numID)) {
                    throw new Exception("Ya esta ese id");
                }

            }
            //Crear Carro
            listaCarros.add(new Carros(numID, marca, modelo, fechaReparacion, estadoReparacion, costoReparacion));

            //Cargar Archivo
            admin.setListaCarros(listaCarros);
            admin.escribirArchivoCarros();
            cargarJtableCarros(jTable_Carros, listaCarros);
            jTextField_Marca.setText("");
            jTextField_Modelo.setText("");
            jTextField_Fecha.setText("");
            jTextField_NumID.setText("");
            jTextField_CostoReparacion.setText("");
            JOptionPane.showMessageDialog(jPanel_CrudEmpleados, "Carro Creado", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jPanel_CrudEmpleados, e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_CrearCarrosMouseClicked

    private void jButton_SeleccionarCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SeleccionarCarroMouseClicked
        //Seleccionar Carro
        Carros carroSelected = (Carros) jComboBox_ModificarCarros.getSelectedItem();
        jTextField_MarcaModificar.setText(carroSelected.getMarca());
        jTextField_ModeloModificar.setText(carroSelected.getModelo());
        jTextField_FechaModificar.setText(dFormat.format(carroSelected.getFechaFabricacion()));
        jTextField_NumIDModificar.setText(carroSelected.getID());
        jTextField_CostoReparacionModificar.setText(Double.toString(carroSelected.getCostoReparacion()));

    }//GEN-LAST:event_jButton_SeleccionarCarroMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //Modificar
        try {
            Carros carroSelected = (Carros) jComboBox_ModificarCarros.getSelectedItem();
            //Cargar archivos
            listaCarros = new ArrayList();
            administrarEmpleado admin = new administrarEmpleado("./Nube/carros.alex");
            admin.cargarArchivoCarros();
            listaCarros = admin.getListaCarros();
            String marca = jTextField_MarcaModificar.getText();
            String modelo = jTextField_ModeloModificar.getText();
            String fecha = jTextField_FechaModificar.getText();
            //Convertir a Date 
            Date fechaReparacion = dFormat.parse(fecha);
            String numID = jTextField_NumIDModificar.getText();
            double costoReparacion = Double.parseDouble(jTextField_CostoReparacionModificar.getText());
            listaCarros = admin.getListaCarros();
            for (Carros listaCarro : listaCarros) {
                if (listaCarro.getID().equals(carroSelected.getID())) {
                    listaCarro.setMarca(marca);
                    listaCarro.setModelo(modelo);
                    listaCarro.setFechaFabricacion(fechaReparacion);
                    listaCarro.setID(numID);
                    listaCarro.setCostoReparacion(costoReparacion);
                }
            }
            //Escribir
            admin.setListaCarros(listaCarros);
            admin.escribirArchivoCarros();
            cargarJtableCarros(jTable_Carros, listaCarros);
            cargarJcomboBoxCarros(jComboBox_ModificarCarros, listaCarros);
            JOptionPane.showMessageDialog(jPanel3, "Carro Modificado", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jPanel3, e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneStateChanged
        //Cargar ComboBox
        listaEmpleado = new ArrayList();
        administrarEmpleado admin = new administrarEmpleado("./Nube/empleado.alex");
        admin.cargarArchivoEmpleado();
        listaEmpleado = admin.getListaEmpleado();
        cargarJcomboBoxEmpleados(jComboBox_EmpleadoReparar, listaEmpleado);
        cargarJcomboBoxCarrosEspera(jComboBox_AutoReparar, listaCarros);
    }//GEN-LAST:event_jTabbedPaneStateChanged

    private void jButton_SIMULARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SIMULARMouseClicked
        Carros carroSelect = (Carros) jComboBox_AutoReparar.getSelectedItem();
        Empleado empleadoSelect = (Empleado) jComboBox_EmpleadoReparar.getSelectedItem();
        //Cargar archivos
        listaCarros = new ArrayList();
        administrarEmpleado admin = new administrarEmpleado("./Nube/carros.alex");
        admin.cargarArchivoCarros();
        listaCarros = admin.getListaCarros();
        for (Carros listaCarro : listaCarros) {
            if (listaCarro.getID().equals(carroSelect.getID())) {
                carroSelect = listaCarro;
            }
        }
        jProgressBar_CargaSimulacion.setMaximum((int) carroSelect.getCostoReparacion());
        HiloProgressBar hilo = new HiloProgressBar(jProgressBar_CargaSimulacion, carroSelect);
        hilo.start();
        Random rnd = new Random();
        int probabilidad = empleadoSelect.getCantCarrosreparadoExito();
        if (probabilidad == 0) {
            switch (carroSelect.getEstadoVehiculo()) {
                case "EN ESPERA" -> {
                    //Modificar a Reparacion
                    carroSelect.setEstadoVehiculo("EN REPARACION");
                    admin.setListaCarros(listaCarros);
                    admin.cargarArchivoCarros();
                    cargarJtableCarros(jTable_Carros, listaCarros);
                    cargarJtableCarrosSimulacion(jTable_Carros, carroSelect, empleadoSelect, true);
 
                }
                case "EN REPARACION" -> {
                }
                case "EN ESPERA DE PAGO DE REPARACION" -> {
                }
                case "SALDO PAGADO" -> {
                }
                case "EN ESPERA DE SER ENTREGADO" -> {
                }
                case "ENTREGADO" -> {
                }
            }
        } else if (probabilidad > 0 && probabilidad <= 5) {
            int numRandom = rnd.nextInt(100);
            if (numRandom > 70) {

            } else {
                JOptionPane.showMessageDialog(jPanel3, "Fallo la reparacion", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else if (probabilidad > 5 && probabilidad <= 15) {
            int numRandom = rnd.nextInt(100);
            if (numRandom > 78) {

            } else {
                JOptionPane.showMessageDialog(jPanel3, "Fallo la reparacion", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else if (probabilidad > 15 && probabilidad <= 30) {
            int numRandom = rnd.nextInt(100);
            if (numRandom > 87) {

            } else {
                JOptionPane.showMessageDialog(jPanel3, "Fallo la reparacion", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else if (probabilidad > 30) {
            int numRandom = rnd.nextInt(100);
            if (numRandom > 93) {

            } else {
                JOptionPane.showMessageDialog(jPanel3, "Fallo la reparacion", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_SIMULARMouseClicked
    public void cargarJtableEmpleado(JTable jTable, ArrayList<Empleado> listaEmpleados) {
        //Agarrar el modelo
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setRowCount(0);
        for (int i = 0; i < listaEmpleados.size(); i++) {
            Empleado empleadoSelected = listaEmpleados.get(i);
            Object[] newRow = {
                empleadoSelected.getNombre(),
                empleadoSelected.getEdad(),
                empleadoSelected.getNumID(),
                empleadoSelected.getCantCarrosreparadoExito()
            };
            model.addRow(newRow);
        }
        jTable.setModel(model);
        jTable.repaint();
        jTable.updateUI();
    }

    public void cargarJtableCarros(JTable jTable, ArrayList<Carros> listaCarros) {
        //Agarrar el modelo
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setRowCount(0);
        for (int i = 0; i < listaCarros.size(); i++) {
            Carros carroSelected = listaCarros.get(i);
            Object[] newRow = {
                carroSelected.getMarca(),
                carroSelected.getModelo(),
                dFormat.format(carroSelected.getFechaFabricacion()),
                carroSelected.getEstadoVehiculo(),
                carroSelected.getCostoReparacion()
            };
            model.addRow(newRow);
        }
        jTable.setModel(model);
        jTable.repaint();
        jTable.updateUI();
    }

    public void cargarJcomboBoxCarros(JComboBox jCombo, ArrayList<Carros> listaCarros) {
        DefaultComboBoxModel modelCombo = new DefaultComboBoxModel();
        for (int i = 0; i < listaCarros.size(); i++) {
            modelCombo.addElement(listaCarros.get(i));
        }
        jCombo.setModel(modelCombo);
    }

    public void cargarJcomboBoxEmpleados(JComboBox jCombo, ArrayList<Empleado> listaEmpleados) {
        DefaultComboBoxModel modelCombo = new DefaultComboBoxModel();
        for (int i = 0; i < listaEmpleados.size(); i++) {
            modelCombo.addElement(listaEmpleados.get(i));
        }
        jCombo.setModel(modelCombo);
    }

    public void cargarJcomboBoxCarrosEspera(JComboBox jCombo, ArrayList<Carros> listaCarros) {
        DefaultComboBoxModel modelCombo = new DefaultComboBoxModel();
        for (int i = 0; i < listaCarros.size(); i++) {
            Carros carrosSelected = listaCarros.get(i);
            if (carrosSelected.getEstadoVehiculo().equals("EN ESPERA")) {
                modelCombo.addElement(listaCarros.get(i));
            }

        }
        jCombo.setModel(modelCombo);
    }

    public void cargarJtableCarrosSimulacion(JTable jTable, Carros carroSelected, Empleado empleadoSelected, boolean exito) {
        //Agarrar el modelo
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        String exitos = "";
        if (exito) {
            exitos = "Si";
        } else {
            exitos = "No";
        }
        Object[] newRow = {
            empleadoSelected.getNombre(),
            carroSelected.getMarca(),
            exitos
        };
        model.addRow(newRow);

        jTable.setModel(model);
        jTable.repaint();
        jTable.updateUI();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen2P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen2P2_AlberthGodoy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_CrearCarros;
    private javax.swing.JButton jButton_CrearEmpleado;
    private javax.swing.JButton jButton_EliminarEmpleado;
    private javax.swing.JButton jButton_SIMULAR;
    private javax.swing.JButton jButton_SeleccionarCarro;
    private javax.swing.JComboBox<String> jComboBox_AutoReparar;
    private javax.swing.JComboBox<String> jComboBox_EmpleadoReparar;
    private javax.swing.JComboBox<String> jComboBox_ModificarCarros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_CrudEmpleados;
    private javax.swing.JProgressBar jProgressBar_CargaSimulacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_Empleados;
    private javax.swing.JScrollPane jScrollPane_Empleados1;
    private javax.swing.JSpinner jSpinner_Edad;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable_Carros;
    private javax.swing.JTable jTable_Empleados;
    private javax.swing.JTable jTable_Simulacion;
    private javax.swing.JTextField jTextField_CostoReparacion;
    private javax.swing.JTextField jTextField_CostoReparacionModificar;
    private javax.swing.JTextField jTextField_Fecha;
    private javax.swing.JTextField jTextField_FechaModificar;
    private javax.swing.JTextField jTextField_Marca;
    private javax.swing.JTextField jTextField_MarcaModificar;
    private javax.swing.JTextField jTextField_Modelo;
    private javax.swing.JTextField jTextField_ModeloModificar;
    private javax.swing.JTextField jTextField_NombreEmpleado;
    private javax.swing.JTextField jTextField_NumID;
    private javax.swing.JTextField jTextField_NumIDModificar;
    private javax.swing.JTextField jTextField_NumIdentidad;
    // End of variables declaration//GEN-END:variables
}
